bed:
  model: bed_1
  model_type: sdf
  position: [ -2.15291190147, -2.62278294563, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]

sink:
  model: sink_1
  model_type: sdf
  position: [ 1.24171398032, -0.94286456318, 0.0 ]
  orientation: [ 0.0, 0.0, 3.14 ]
  
burner_stove:
  model: burner_stove_1
  model_type: sdf
  position: [ 2.13275506255, -0.915840491309, 0.0 ]
  orientation: [ 0.0, 0.0, -3.14 ]
  
table_ikea_bjursta:
  model: table_ikea_bjursta
  model_type: sdf
  position: [ 1.77236080355, 1.38153609543, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
    
chair_ikea_borje2:
  model: chair_ikea_borje2
  model_type: sdf
  position: [ 1.71637, 1.95474, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

couch_1:
  model: couch_1
  model_type: sdf
  position: [ -1.39630586056, 0.261605174699, 0.0 ]
  orientation: [ 0.0, 0.0, 3.14 ]
  
table_living_room:
  model: table_living_room
  model_type: sdf
  position: [ -1.41423, 2.12579, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
  
cabinet_ikea_malm_small:
  model: cabinet_ikea_malm_small
  model_type: sdf
  position: [ -1.29853, -3.40959, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
  
bathroom_set:
  model: bathroom_set
  model_type: sdf
  position: [ 1.18786466964, -3.31917666627, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]

